# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 박종혁
title: Junior Back-end Developer
email: pjongk148@gmail.com
Blog: https://velog.io/@pjongk148

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  pjongk148
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-image.jpg
about_content: | # this will include new lines to allow paragraphs
  적극적인 의사소통과 피드백을 통한 작업 능률 향상을 지향하는 신입 백엔드 개발자 박종혁입니다.
  본 전공은 해양과학이었으나 졸업 이후 Java, Spring Boot 를 통한 웹 애플리케이션 개발 교육을 이수하였고 이를 토대로 팀 프로젝트를 진행하였습니다.
  협업의 중요성과 즐거움을 알고, 적극적인 피드백과 의사소통을 통한 작업 능률 향상을 지향합니다.
  또한 꾸준함을 통한 성장의 즐거움을 알기에 당일 학습한 내용을 커밋하거나 블로깅하고자 노력하고 있습니다.
  


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 도서나눔 서비스 북빌리지
        link: github.com/codestates-seb/seb41_main_015
        # link_text: Project Websitㅊㄷe
        additional_links:
          - title:  bookvillage-project
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >

        description: | # this will include new lines to allow paragraphs
          도서나눔 서비스 북빌리지

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 코드 스테이츠(CODE STATES)
        sub_title: Software Engineering Bootcamp Backend corse
        caption: 2022.08.19 - 2023.02.10
        description: | # this will include new lines to allow paragraphs
          - Java, Spring Boot, DB 기초 지식 교육
          - 1일 1커밋 스터디 활동
          - 프론트엔드/백엔드 협업을 통한 프로젝트 2회 진행

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 인하대학교
        caption: 2014 - 2022
        sub_title: 해양과학
        description: | # this will include new lines to allow paragraphs
          - 2018 3-2 학기 성적우수장학생 수상
          

  - title: Certificates
    layout: list
  content:
    - layout: left
      title: OPIc
      caption: 2022.09.11 취득
      description: | # this will include new lines to allow paragraphs
        IM2

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
